
# Aplikasi KAL

## Pagerank
PageRank (PR) adalah algoritma pencarian yang digunakan oleh Google Search untuk memberi peringkat halaman web, dalam mengukur seberapa pentingnya bagi pengguna di hasil mesin pencarian mereka.

Menurut Google:

PageRank bekerja dengan menghitung jumlah dan kualitas tautan ke suatu halaman untuk menentukan perkiraan kasar seberapa penting situs web tersebut. Asumsi yang mendasarinya adalah bahwa situs web yang lebih penting cenderung menerima lebih banyak tautan dari situs web lainnya.

Saat ini, PageRank bukan satu-satunya algoritma pencarian yang digunakan oleh Google untuk mengurutkan hasil penelusuran, tetapi merupakan algoritma pertama yang digunakan oleh perusahaan itu, dan merupakan algoritma yang paling terkenal.Mulai 24 September 2019, PageRank dan semua paten terkaitnya sudah kedaluwarsa, sehingga tak dipakai lagi

### Konsep

Banyak cara digunakan search engine dalam menentukan kualitas/rangking sebuah halaman web, mulai dari penggunaan META Tags, isi dokumen, penekanan pada content dan masih banyak teknik lain atau gabungan teknik yang mungkin digunakan. Link popularity, sebuah teknologi yang dikembangkan untuk memperbaiki kekurangan dari teknologi lain (Meta Keywords, Meta Description) yang bisa dicurangi dengan halaman yang khusus di desain untuk search engine atau biasa disebut doorway pages. Dengan algoritma ‘PageRank’ ini, dalam setiap halaman akan diperhitungkan inbound link (link masuk) dan outbound link (link keuar) dari setiap halaman web.

PageRank, memiliki konsep dasar yang sama dengan link popularity, tetapi tidak hanya memperhitungkan “jumlah” inbound dan outbound link. Pendekatan yang digunakan adalah sebuah halaman akan diangap penting jika halaman lain memiliki link ke halaman tersebut. Sebuah halaman juga akan menjadi semakin penting jika halaman lain yang memiliki rangking (pagerank) tinggi mengacu ke halaman tersebut.

Dengan pendekatan yang digunakan PageRank, proses terjadi secara rekursif dimana sebuah rangking akan ditentukan oleh rangking dari halaman web yang rangkingnya ditentukan oleh rangking halaman web lain yang memiliki link ke halaman tersebut. Proses ini berarti suatu proses yang berulang (rekursif). Di dunia maya, ada jutaan bahkan milyaran halaman web. Oleh karena itu sebuah rangking halaman web ditentukan dari struktur link dari keseluruhan halaman web yang ada di dunia maya. Sebuah proses yang sangat besar dan komplek.

### Algoritma

Dari pendekatan yang sudah dijelaskan pada artikel konsep pagerank, Lawrence Page and Sergey Brin membuat algoritma pagerank seperti di bawah:

Algoritma awal

$$ \text{PR}(A) = (1-d) + d \left( \frac{\text{PR}(T_1)}{C(T_1)} + \cdots + \frac{\text{PR}(T_n)}{C(T_n)} \right)$$

Salah satu algoritma lain yang dipublikasikan

$$PR(A) = \frac{(1-d)}{N} + d \left( \frac{PR(T1)}{C(T1)} + \ldots + \frac{PR(Tn)}{C(Tn)} \right)$$

PR(A) adalah Pagerank halaman A

PR(T1) adalah Pagerank halaman T1 yang mengacu ke halaman A

C(T1) adalah jumlah link keluar (outbound link) pada halaman T1

d adalah damping factor yang bisa diberi antara 0 dan 1.

N adalah jumlah keseluruhan halaman web (yang terindeks oleh Google)

Dari algoritma di atas dapat dilihat bahwa pagerank ditentukan untuk setiap halaman anda bukan keseluruhan situs web. Pagerank sebuah halaman ditentukan dari pagerank halaman yang mengacu kepadanya yang juga menjalani proses penentuan pagerank dengan cara yang sama, jadi proses ini akan berulang sampai ditemukan hasil yang tepat.

Akan tetapi pagerank halaman A tidak langsung diberikan kepada halaman yang dituju, akan tetapi sebelumnya dibagi dengan jumlah link yang ada pada halaman T1 (outbound link), dan pagerank itu akan dibagi rata kepada setiap link yang ada pada halaman tersebut. Demikian juga dengan setiap halaman lain “Tn” yang mengacu ke halaman “A”.

Setelah semua pagerank yang didapat dari halaman-halaman lain yang mengacu ke halaman “A” dijumlahkan, nilai itu kemudian dikalikan dengan damping factor yang bernilai antara 0 sampai 1. Hal ini dilakukan agar tidak keseluruhan nilai pagerank halaman T didistribusikan ke halaman A.

### Implementasi

dari algoritma tersebut dapat di dapat matrik yang di hasilkan dari banyaknya edge atau link yang menghubungkan page satu dengan page lainnya.

yaitu matriks A yang menyatakan hubungan page 1 2 3 dan 4:
$$
A = \begin{bmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0 \\
\end{bmatrix}
$$

Untuk mengetahui urutan page yang memiliki pengaruh penting atau yang banyak di rujuk oleh page" lainnya di gunakannlah algoritma PageRank dengan mengalikan matrik A dengan V sebagai indikator. V adalah matrik n X 1 yang memiliki jumlah total 1 dengan n yaitu banyaknya page yang di bandingkan.

dari hasil perkalian A X V menghasilkan Vn dengan n adalah jumlah iterasi yang dilakukan Vn nantinya akan di kalikan kembali dengan A sehingga menghasilkan angka dengan Vn-(Vn-1) memiliki selisih sedikit atau sama dengan dengan nilai toleransi lebih kecil memperngaruhi ke akuratan data yang di dapatkan nantinya

In [ ]:


import numpy as np
A= np.array([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,1/2],[1/3,1/2,0,0]])
V= np.array([[0.50],[0.25],[0.50],[0.25]])
v1=A@V
a= np.zeros_like(V)
b=1
print(V)
while not np.allclose(a,A@V):
  a= A@V
  V=A@V
  b+=1
  print(f'iterasi ke : {b}')
  print(a)

[[0.5 ]
 [0.25]
 [0.5 ]
 [0.25]]
iterasi ke : 2
[[0.625     ]
 [0.16666667]
 [0.41666667]
 [0.29166667]]
iterasi ke : 3
[[0.5625    ]
 [0.20833333]
 [0.4375    ]
 [0.29166667]]
iterasi ke : 4
[[0.58333333]
 [0.1875    ]
 [0.4375    ]
 [0.29166667]]
iterasi ke : 5
[[0.58333333]
 [0.19444444]
 [0.43402778]
 [0.28819444]]
iterasi ke : 6
[[0.578125  ]
 [0.19444444]
 [0.43576389]
 [0.29166667]]
iterasi ke : 7
[[0.58159722]
 [0.19270833]
 [0.43576389]
 [0.28993056]]
iterasi ke : 8
[[0.58072917]
 [0.19386574]
 [0.43518519]
 [0.29021991]]
iterasi ke : 9
[[0.58029514]
 [0.19357639]
 [0.43561921]
 [0.29050926]]
iterasi ke : 10
[[0.58087384]
 [0.19343171]
 [0.43547454]
 [0.29021991]]
iterasi ke : 11
[[0.58058449]
 [0.19362461]
 [0.43545042]
 [0.29034047]]
iterasi ke : 12
[[0.58062066]
 [0.19352816]
 [0.43551071]
 [0.29034047]]
iterasi ke : 13
[[0.58068094]
 [0.19354022]
 [0.43547454]
 [0.2903043 ]]
iterasi ke : 14
[[0.58062669]
 [0.19356031]
 [0.43548257]
 [0.29033042]]
iterasi ke : 15
[[0.580647

In [ ]:
import numpy as np
A= np.array([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,1/2],[1/3,1/2,0,0]])
V= np.array([[0.50],[0.25],[0.50],[0.25]])
v1=A@V
a= np.zeros_like(V)
b=1
print(V)
error = 0.001
while not np.allclose(a,A@V, atol=error):
  a= A@V
  V=A@V
  b+=1
  print(f'iterasi ke : {b}')
  print(a)

[[0.5 ]
 [0.25]
 [0.5 ]
 [0.25]]
iterasi ke : 2
[[0.625     ]
 [0.16666667]
 [0.41666667]
 [0.29166667]]
iterasi ke : 3
[[0.5625    ]
 [0.20833333]
 [0.4375    ]
 [0.29166667]]
iterasi ke : 4
[[0.58333333]
 [0.1875    ]
 [0.4375    ]
 [0.29166667]]
iterasi ke : 5
[[0.58333333]
 [0.19444444]
 [0.43402778]
 [0.28819444]]
iterasi ke : 6
[[0.578125  ]
 [0.19444444]
 [0.43576389]
 [0.29166667]]
iterasi ke : 7
[[0.58159722]
 [0.19270833]
 [0.43576389]
 [0.28993056]]
iterasi ke : 8
[[0.58072917]
 [0.19386574]
 [0.43518519]
 [0.29021991]]


In [ ]:
import numpy as np

# Define the matrices and initial vector
A = np.array([[0, 0, 1, 1/2],
              [1/3, 0, 0, 0],
              [1/3, 1/2, 0, 1/2],
              [1/3, 1/2, 0, 0]])
V = np.array([[0.20], [0.50], [0.15], [0.15]])

# Initialize variables
a = np.zeros_like(V)
b = 1
error = 0.01

# Print initial vector
print("Initial V:")
print(V)

# Iteration loop with custom error threshold
while np.max(np.abs(A@V - a)) > error:
    a = A@V
    V = A@V
    b += 1
    print(f'Iteration: {b}')
    print(a)

# Print final result
print("Final V:")
print(V)


Initial V:
[[0.2 ]
 [0.5 ]
 [0.15]
 [0.15]]
Iteration: 2
[[0.225     ]
 [0.06666667]
 [0.39166667]
 [0.31666667]]
Iteration: 3
[[0.55      ]
 [0.075     ]
 [0.26666667]
 [0.10833333]]
Iteration: 4
[[0.32083333]
 [0.18333333]
 [0.275     ]
 [0.22083333]]
Iteration: 5
[[0.38541667]
 [0.10694444]
 [0.30902778]
 [0.19861111]]
Iteration: 6
[[0.40833333]
 [0.12847222]
 [0.28125   ]
 [0.18194444]]
Iteration: 7
[[0.37222222]
 [0.13611111]
 [0.29131944]
 [0.20034722]]
Iteration: 8
[[0.39149306]
 [0.12407407]
 [0.29230324]
 [0.19212963]]
Final V:
[[0.39149306]
 [0.12407407]
 [0.29230324]
 [0.19212963]]
