#Sifat Determinan Matriks

##A. macam- macam Contoh matriks

In [ ]:
import numpy as np

A = np.array([[1, 0], [0, 1]])  # matriks identitas
B = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])  # matriks identitas
C = np.array([[1, 2, 1], [3, 1, 2], [2, 1, 2]])  # matriks identitas
D = np.array([[1, 2, 1], [2, 1, 2], [3, 1, 2]])  # merubah baris 2 dengan 3
E = np.array([[1, 2, 1], [2, 4, 2], [2, 1, 1]])  # matriks dengan mengubah baris 2 dengan 3
F = np.array([[1, 2, 1], [2, 4, 2], [2, 1, 2]])  # matriks dengan kolom yang merupakan kelipatan dari baris lainnya
G = np.array([[1, 2, 1], [2, 4, 2], [2, 4, 3]])  # matriks dengan kolom yang merupakan kelipatan dari kolom lainnya
H = np.array([[6, 2, 4], [2, 4, 2], [4, 2, 4]])  # merubah baris 2 dengan 3
I = np.array([[3, 4], [2, 1]])  # matriks identitas
J = np.array([[6, 8], [4, 2]])  # matriks identitas
K = np.array([[6, 4], [4, 1]])  # kolom sama
L = np.array([[6, 8], [2, 1]])  # baris sama
M = np.array([[4, 1], [2, 1]])  # baris sama
N = np.array([[7, 5], [2, 1]])  # baris sama
O = np.array([[1, 3, 2], [0, 2, 2], [0, 0, 1]])  # merubah baris 2 dengan 3
P = np.array([[1, 0, 0], [1, 2, 0], [1, 2, 1]])  # merubah baris 2 dengan 3
Q = np.array([[2, 1], [1, 1]])  # baris sama
R = np.array([[1, 1], [1, 1]])  # baris sama
S = np.array([[3, 2], [3, 2]])  # baris sama
T = np.array([[3, 1, 2],[2, 1, 2], [4, 2, 1]])
U = np.array([[]])
#Cetak matrks
print("Cetak Matriks:")
print("Matriks A:")
print(A)
print()

print("Matriks B:")
print(B)
print()

print("Matriks C:")
print(C)
print()

print("Matriks D:")
print(D)
print()

print("Matriks E:")
print(E)
print()

print("Matriks F:")
print(F)
print()

print("Matriks G:")
print(G)
print()

print("Matriks H:")
print(H)
print()

print("Matriks I:")
print(I)
print()

print("Matriks J:")
print(J)
print()

print("Matriks K:")
print(K)
print()

print("Matriks L:")
print(L)
print()

print("Matriks M:")
print(M)
print()

print("Matriks N:")
print(N)
print()

print("Matriks O:")
print(O)
print()

print("Matriks P:")
print(P)
print()

print("Matriks Q:")
print(Q)
print()

print("Matriks R:")
print(R)
print()

print("Matriks S:")
print(S)

print("matriks T:")
print(T)

Cetak Matriks:
Matriks A:
[[1 0]
 [0 1]]

Matriks B:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Matriks C:
[[1 2 1]
 [3 1 2]
 [2 1 2]]

Matriks D:
[[1 2 1]
 [2 1 2]
 [3 1 2]]

Matriks E:
[[1 2 1]
 [2 4 2]
 [2 1 1]]

Matriks F:
[[1 2 1]
 [2 4 2]
 [2 1 2]]

Matriks G:
[[1 2 1]
 [2 4 2]
 [2 4 3]]

Matriks H:
[[6 2 4]
 [2 4 2]
 [4 2 4]]

Matriks I:
[[3 4]
 [2 1]]

Matriks J:
[[6 8]
 [4 2]]

Matriks K:
[[6 4]
 [4 1]]

Matriks L:
[[6 8]
 [2 1]]

Matriks M:
[[4 1]
 [2 1]]

Matriks N:
[[7 5]
 [2 1]]

Matriks O:
[[1 3 2]
 [0 2 2]
 [0 0 1]]

Matriks P:
[[1 0 0]
 [1 2 0]
 [1 2 1]]

Matriks Q:
[[2 1]
 [1 1]]

Matriks R:
[[1 1]
 [1 1]]

Matriks S:
[[3 2]
 [3 2]]
matriks T:
[[3 1 2]
 [2 1 2]
 [4 2 1]]


##B. menghitung determinan

In [ ]:
# Hitung determinan masing-masing matriks
detA = np.linalg.det(A)
detB = np.linalg.det(B)
detC = np.linalg.det(C)
detD = np.linalg.det(D)
detE = np.linalg.det(E)
detF = np.linalg.det(F)
detG = np.linalg.det(G)
detH = np.linalg.det(H)
detI = np.linalg.det(I)
detJ = np.linalg.det(J)
detK = np.linalg.det(K)
detL = np.linalg.det(L)
detM = np.linalg.det(M)
detN = np.linalg.det(N)
detO = np.linalg.det(O)
detP = np.linalg.det(P)
detQ = np.linalg.det(Q)
detR = np.linalg.det(R)
detS = np.linalg.det(S)
detT = np.linalg.det(T)


##C. Sifat-Sifat Determinan

In [ ]:
#Sifat-Sifat determinan
print("Sifat-Sifat determinan")
print("determinan Matriks")
# Matriks identitas memiliki determinan 1.
print("Determinan A (matriks identitas):", int(detA))
print("Determinan B (matriks identitas):", int(detB))
# matriks C
print("Determinan C matriks C: ",int(detC))
# matriks c dengan merubah baris akan mengubah tanda dari determinan
print("Determinan D (matriks c dengan merubah baris akan mengubah tanda dari determinan):",int(detD))
# Jika suatu baris matriks adalah kelipatan dari baris lainnya, determinannya akan menjadi nol.
print("Determinan E (baris 2 merupakan kelipatan dari baris 3):", int(detE))

# Jika suatu kolom matriks adalah kelipatan dari kolom lainnya, determinannya juga akan menjadi nol.
print("Determinan F (kolom 3 merupakan kelipatan dari kolom 1):", int(detF))
print("Determinan G (kolom 3 merupakan kelipatan dari kolom 2):", int(detG))

# Untuk matriks yang merupakan kelipatan dari matriks lainnya, determinannya adalah kelipatan pangkat ordo dari matriks tersebut, dikalikan dengan determinan matriks kelipatannya.
print("Determinan H (matriks H merupakan kelipatan dari matriks C):", int(detH))
# Jika suatu matriks adalah hasil penjumlahan dari dua matriks, determinannya adalah hasil penjumlahan determinan matriks-matriks tersebut.
print("Determinan M (hasil penjumlahan matriks K dan L):", detM)

# Jika suatu matriks membentuk segitiga atas dengan nol di atas atau di bawah diagonal, determinannya adalah hasil perkalian diagonalnya.
print("Determinan N (matriks N membentuk segitiga atas):", detN)

# Jika dua matriks dikalikan, determinan dari hasil matriks adalah hasil perkalian determinan matriks tersebut.
print("Determinan P (hasil perkalian matriks O dan Q):", detP)
print("Determinan Q (matriks Q):", detQ)
print("determinan T:",detT)

Sifat-Sifat determinan
determinan Matriks
Determinan A (matriks identitas): 1
Determinan B (matriks identitas): 1
Determinan C matriks C:  -3
Determinan D (matriks c dengan merubah baris akan mengubah tanda dari determinan): 3
Determinan E (baris 2 merupakan kelipatan dari baris 3): 0
Determinan F (kolom 3 merupakan kelipatan dari kolom 1): 0
Determinan G (kolom 3 merupakan kelipatan dari kolom 2): 0
Determinan H (matriks H merupakan kelipatan dari matriks C): 24
Determinan M (hasil penjumlahan matriks K dan L): 2.0
Determinan N (matriks N membentuk segitiga atas): -2.9999999999999982
Determinan P (hasil perkalian matriks O dan Q): 2.0
Determinan Q (matriks Q): 1.0
determinan T: -2.9999999999999996


In [3]:
import numpy as np

# Matriks baru
x = np.array([[2, 3, 4, 3, 4],
              [2, 2, 1, 3, 6],
              [4, 3, 1, 4, 2],
              [6, 2, 1, 4, 2],
              [4, 3, 8, 4, 1]])

print("Matriks X:")
print(x)

# Submatriks manual
x11 = np.array([[2, 1, 3, 6], [3, 1, 4, 2], [2, 1, 4, 2], [3, 8, 4, 1]])
x12 = np.array([[2, 1, 3, 6], [4, 1, 4, 2], [6, 1, 4, 2], [4, 8, 4, 1]])
x13 = np.array([[2, 2, 3, 6], [4, 3, 4, 2], [6, 2, 4, 2], [4, 3, 4, 1]])
x14 = np.array([[2, 2, 1, 6], [4, 3, 1, 2], [6, 2, 1, 2], [4, 3, 8, 1]])
x15 = np.array([[2, 2, 1, 3], [4, 3, 1, 4], [6, 2, 1, 4], [4, 3, 8, 4]])

x21 = np.array([[3, 4, 3, 4], [3, 1, 4, 2], [2, 1, 4, 2], [3, 8, 4, 1]])
x22 = np.array([[2, 4, 3, 4], [4, 1, 4, 2], [6, 1, 4, 2], [4, 8, 4, 1]])
x23 = np.array([[2, 3, 3, 4], [4, 3, 4, 2], [6, 2, 4, 2], [4, 3, 4, 1]])
x24 = np.array([[2, 3, 4, 4], [4, 3, 1, 2], [6, 2, 1, 2], [4, 3, 8, 1]])
x25 = np.array([[2, 3, 4, 3], [4, 3, 1, 4], [6, 2, 1, 4], [4, 3, 8, 4]])

x31 = np.array([[3, 4, 3, 4], [2, 1, 3, 6], [2, 1, 4, 2], [3, 8, 4, 1]])
x32 = np.array([[2, 4, 3, 4], [2, 1, 3, 6], [6, 1, 4, 2], [4, 8, 4, 1]])
x33 = np.array([[2, 3, 3, 4], [2, 2, 3, 6], [6, 2, 4, 2], [4, 3, 4, 1]])
x34 = np.array([[2, 3, 4, 4], [2, 2, 1, 6], [6, 2, 1, 2], [4, 3, 8, 1]])
x35 = np.array([[2, 3, 4, 3], [2, 2, 1, 3], [6, 2, 1, 4], [4, 3, 8, 4]])

x41 = np.array([[3, 4, 3, 4], [2, 1, 3, 6], [3, 1, 4, 2], [3, 8, 4, 1]])
x42 = np.array([[2, 4, 3, 4], [2, 1, 3, 6], [4, 1, 4, 2], [4, 8, 4, 1]])
x43 = np.array([[2, 3, 3, 4], [2, 2, 3, 6], [4, 3, 4, 2], [4, 3, 4, 1]])
x44 = np.array([[2, 3, 4, 4], [2, 2, 1, 6], [4, 3, 1, 2], [4, 3, 8, 1]])
x45 = np.array([[2, 3, 4, 3], [2, 2, 1, 3], [4, 3, 1, 4], [4, 3, 8, 4]])

x51 = np.array([[3, 4, 3, 4], [2, 1, 3, 6], [3, 1, 4, 2], [2, 1, 4, 2]])
x52 = np.array([[2, 4, 3, 4], [2, 1, 3, 6], [4, 1, 4, 2], [6, 1, 4, 2]])
x53 = np.array([[2, 3, 3, 4], [2, 2, 3, 6], [4, 3, 4, 2], [6, 2, 4, 2]])
x54 = np.array([[2, 3, 4, 4], [2, 2, 1, 6], [4, 3, 1, 2], [6, 2, 1, 2]])
x55 = np.array([[2, 3, 4, 3], [2, 2, 1, 3], [4, 3, 1, 4], [6, 2, 1, 4]])

# Menghitung determinan submatriks
det_11 = np.linalg.det(x11)
det_12 = np.linalg.det(x12)
det_13 = np.linalg.det(x13)
det_14 = np.linalg.det(x14)
det_15 = np.linalg.det(x15)

det_21 = np.linalg.det(x21)
det_22 = np.linalg.det(x22)
det_23 = np.linalg.det(x23)
det_24 = np.linalg.det(x24)
det_25 = np.linalg.det(x25)

det_31 = np.linalg.det(x31)
det_32 = np.linalg.det(x32)
det_33 = np.linalg.det(x33)
det_34 = np.linalg.det(x34)
det_35 = np.linalg.det(x35)

det_41 = np.linalg.det(x41)
det_42 = np.linalg.det(x42)
det_43 = np.linalg.det(x43)
det_44 = np.linalg.det(x44)
det_45 = np.linalg.det(x45)

det_51 = np.linalg.det(x51)
det_52 = np.linalg.det(x52)
det_53 = np.linalg.det(x53)
det_54 = np.linalg.det(x54)
det_55 = np.linalg.det(x55)

# Menghitung kofaktor
c11 = (-1)**(1+1) * det_11
c12 = (-1)**(1+2) * det_12
c13 = (-1)**(1+3) * det_13
c14 = (-1)**(1+4) * det_14
c15 = (-1)**(1+5) * det_15

c21 = (-1)**(2+1) * det_21
c22 = (-1)**(2+2) * det_22
c23 = (-1)**(2+3) * det_23
c24 = (-1)**(2+4) * det_24
c25 = (-1)**(2+5) * det_25

c31 = (-1)**(3+1) * det_31
c32 = (-1)**(3+2) * det_32
c33 = (-1)**(3+3) * det_33
c34 = (-1)**(3+4) * det_34
c35 = (-1)**(3+5) * det_35

c41 = (-1)**(4+1) * det_41
c42 = (-1)**(4+2) * det_42
c43 = (-1)**(4+3) * det_43
c44 = (-1)**(4+4) * det_44
c45 = (-1)**(4+5) * det_45

c51 = (-1)**(5+1) * det_51
c52 = (-1)**(5+2) * det_52
c53 = (-1)**(5+3) * det_53
c54 = (-1)**(5+4) * det_54
c55 = (-1)**(5+5) * det_55

# Membentuk matriks kofaktor
Kof_Matrix_S = np.array([[c11, c12, c13, c14, c15],
                         [c21, c22, c23, c24, c25],
                         [c31, c32, c33, c34, c35],
                         [c41, c42, c43, c44, c45],
                         [c51, c52, c53, c54, c55]])

print("\nMatriks Kofaktor:")
print(Kof_Matrix_S)

# Transpos dari matriks kofaktor
Trans_Kof_Matrix_S = Kof_Matrix_S.transpose()
print("\nTranspos dari Matriks Kofaktor:")
print(Trans_Kof_Matrix_S)

# Menghitung determinan matriks x
det_x = np.linalg.det(x)

# Menghitung invers
invers_manual = (1 / det_x) * Trans_Kof_Matrix_S
print("\nInvers Matriks secara Manual:")
print(invers_manual)


Matriks X:
[[2 3 4 3 4]
 [2 2 1 3 6]
 [4 3 1 4 2]
 [6 2 1 4 2]
 [4 3 8 4 1]]

Matriks Kofaktor:
[[ 127.  254.    6. -340.   42.]
 [ -83. -166.    2.  200.   14.]
 [ -93.    2.  -34.  172.  -50.]
 [ 116.   44.    4. -164.   28.]
 [ -56. -112.   24.  144.  -20.]]

Transpos dari Matriks Kofaktor:
[[ 127.  -83.  -93.  116.  -56.]
 [ 254. -166.    2.   44. -112.]
 [   6.    2.  -34.    4.   24.]
 [-340.  200.  172. -164.  144.]
 [  42.   14.  -50.   28.  -20.]]

Invers Matriks secara Manual:
[[ 0.67553191 -0.44148936 -0.49468085  0.61702128 -0.29787234]
 [ 1.35106383 -0.88297872  0.0106383   0.23404255 -0.59574468]
 [ 0.03191489  0.0106383  -0.18085106  0.0212766   0.12765957]
 [-1.80851064  1.06382979  0.91489362 -0.87234043  0.76595745]
 [ 0.22340426  0.07446809 -0.26595745  0.14893617 -0.10638298]]
