# MATRIKS INVERS

##Pengertian Matriks Invers:

Matriks invers adalah matriks yang ketika dikalikan dengan matriks asalnya akan menghasilkan matriks identitas. Jika suatu matriks $ A $ memiliki invers $ A^{-1} $, maka $ A \times A^{-1} = A^{-1} \times A = I $, di mana $ I $ adalah matriks identitas yang memiliki elemen $ 1 $ di diagonal utamanya dan $ 0 $ di seluruh elemen lainnya.

Secara matematis, jika $ A $ adalah suatu matriks, $ A^{-1} $ adalah invers dari $ A $, dan $ I $ adalah matriks identitas, maka $ A \times A^{-1} = A^{-1} \times A = I $.

Matriks invers hanya ada untuk matriks persegi yang non-singular, yaitu matriks yang memiliki determinan tidak sama dengan nol. Jika determinan matriks $ A $ adalah nol, maka matriks $ A $ tidak memiliki invers.

Matriks invers sering digunakan dalam pemecahan sistem persamaan linier, transformasi geometri, dan dalam berbagai aplikasi matematika, ilmu komputer, dan rekayasa.


##Sifat-sifat Matriks Invers:

1. Unik: Setiap matriks persegi yang memiliki invers, inversnya adalah unik. Artinya, jika suatu matriks memiliki invers, maka tidak mungkin ada dua invers yang berbeda untuk matriks tersebut.

2. Matriks Identitas: Jika suatu matriks $ A $ dapat dikalikan dengan matriks inversnya, hasilnya adalah matriks identitas. Dengan kata lain, jika $ A $ adalah matriks dan $ A^{-1} $ adalah inversnya, maka $ A \times A^{-1} = A^{-1} \times A = I $, di mana $ I $ adalah matriks identitas.

3. Operasi Pembalikan: Jika $ A $ dan $ B $ adalah matriks persegi yang dapat diinvers, maka hasil perkalian matriks invers $ A $ dengan $ B $ juga akan diinvers, dan inversnya adalah $ B $ diikuti oleh $ A $. Dalam simbol, jika $ A^{-1} $ adalah invers dari $ A $ dan $ B^{-1} $ adalah invers dari $ B $, maka $ (AB)^{-1} = B^{-1}A^{-1} $.

4. Pembagian oleh Nol: Matriks tidak dapat diinvers jika determinannya adalah nol. Jika determinan matriks $ A $ adalah nol ( $ \text{det}(A) = 0 $ ), maka $ A $ tidak memiliki invers.

5. Transpos: Transpos dari invers matriks adalah invers dari transpos matriks. Dengan kata lain, jika $ A^{-1} $ adalah invers dari matriks $ A $, maka $ (A^T)^{-1} = (A^{-1})^T $.

6. Perkalian Skalar: Matriks invers dari suatu matriks dapat diperoleh dengan mengalikan inversnya dengan suatu skalar. Jika $ A^{-1} $ adalah invers dari matriks $ A $, maka $ (kA)^{-1} = \frac{1}{k}A^{-1} $, di mana $ k $ adalah skalar bukan nol.


##solusi sistem persamaan linier dengan matriks invers

In [ ]:
import numpy as np

# Matriks 6x6 contoh
A = np.array([[2, 1, 0, 0, 0, 0],
              [1, 2, 1, 0, 0, 0],
              [0, 1, 2, 1, 0, 0],
              [0, 0, 1, 2, 1, 0],
              [0, 0, 0, 1, 2, 1],
              [0, 0, 0, 0, 1, 2]])

# Implementasi fungsi-fungsi eliminasi Gauss

def RowSwap(A, k, l):
    m = A.shape[0]
    n = A.shape[1]
    B = np.copy(A).astype('float64')
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
    return B

def RowScale(A, k, scale):
    m = A.shape[0]
    n = A.shape[1]
    B = np.copy(A).astype('float64')
    for j in range(n):
        if j == k:
            B[k][j] *= scale
    return B

def RowAdd(A, k, l, scale):
    m = A.shape[0]
    n = A.shape[1]
    B = np.copy(A).astype('float64')
    for j in range(n):
        B[l][j] += B[k][j] * scale
    return B

# Proses eliminasi Gauss
n = A.shape[0]
for k in range(n):
    for i in range(k + 1, n):
        if A[i][k] != 0:
            A = RowAdd(A, k, i, -A[i][k] / A[k][k])

print("Matriks setelah eliminasi Gauss:")
print(A)

# Invers matriks dengan eliminasi Gauss-Jordan
for k in range(n):
    A = RowScale(A, k, 1 / A[k][k])
    for i in range(n):
        if i != k:
            A = RowAdd(A, k, i, -A[i][k])

print("\nInvers matriks:")
print(A)

# Simpan hasil invers matriks ke dalam variabel baru
A_invers = A

# Matriks solusi konstanta
konstanta = np.array([1, 2, 3, 4, 5, 6])

# Perkalian matriks invers dengan matriks solusi konstanta
hasil = np.dot(A_invers, konstanta)
print("\nHasil perkalian A invers dengan matriks solusi konstanta:")
print(hasil)

# Perkalian menggunakan operator @ (dot product)
hasil = A_invers @ konstanta
print("\nHasil perkalian A invers dengan matriks solusi konstanta (menggunakan operator @):")
print(hasil)
z= A_invers@hasil
y= A_invers@A
print(z)
print(y)
print(hasil)
# perkalian tanpa menggunakan @
for i in range(n):
    for j in range(n):
        hasil[i] += A_invers[i][j] * konstanta[j]

print("\nHasil perkalian A invers dengan matriks solusi konstanta (tanpa menggunakan @ atau np.dot()):")
print(hasil)

Matriks setelah eliminasi Gauss:
[[2.         1.         0.         0.         0.         0.        ]
 [0.         1.5        1.         0.         0.         0.        ]
 [0.         0.         1.33333333 1.         0.         0.        ]
 [0.         0.         0.         1.25       1.         0.        ]
 [0.         0.         0.         0.         1.2        1.        ]
 [0.         0.         0.         0.         0.         1.16666667]]

Invers matriks:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Hasil perkalian A invers dengan matriks solusi konstanta:
[1. 2. 3. 4. 5. 6.]

Hasil perkalian A invers dengan matriks solusi konstanta (menggunakan operator @):
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[1. 2. 3. 4. 5. 6.]


##soal matriks 6 variavel atau 6 persamaan
$$
\begin{bmatrix}
2x_1 + x_2 &= 0 \\
x_1 + 3x_2 + 4x_3 &= 0 \\
4x_2 + 5x_3 + 6x_4 &= 0 \\
6x_3 + 7x_4 + 8x_5 &= 0 \\
8x_4 + 9x_5 + 10x_6 &= 0 \\
10x_5 + 11x_6 &= 0 \\
\end{bmatrix}
$$




